---
- name: Exo 2
  hosts: slave1
  gather_facts: yes  # on indique clairement que ces variables  seront utiles.
 
  tasks:
  - name: Mouve file
    file: path=private state=directory
  
  - name: Copy file
    copy: 
      src: files/secret.txt
      dest: private/secret.txt

  - name: Replace in file
    replace:
      dest: private/secret.txt
      regexp: '\[father\]'
      replace: '{{ansible_hostname}}'   
  
  
...