- name: Final EXO 7
  hosts: slave1
  gather_facts: yes
  

  # variables declaration
  vars:
    #groups: [dev, sudo]
    user:  {name: dev1, pwd: dev1 }
    prof: Christophe
    endpoint:  "http://localhost/dev1/{{user.name}}.html"
  
  # here the tasks will start
  tasks:


  - name: Install apache
    
    apt:
      name: apache2
      state: present
      update_cache: yes    
    become: yes            
    when: ansible_distribution == "Ubuntu"

  - name: Start-apache
    service:
      name: apache2
      state: started
    become: yes
  

  - name: create groups
    group:
      name: "{{ item }}"
      state: present
    loop:
      - dev
      - sudo
    become: yes

  
  - name: create user {{ user.name }}
    user:
      state: present
      name: "{{user.name}}"
      group: "{{item}}"
      password: "{{ user.pwd | password_hash('sha512')}}"
    loop:
      - dev
      - sudo
    become: yes
  
  # create dv1 folder and changing it owner

  - name: Update dev1 folder owner 
    file:
       state: directory
       path: /var/www/html/{{user.name}}
       owner: "{{ ansible_user }}"
    become: yes
 
  
  - name: copy user.html.j2 dans le dossier /var/www/html/dev1
    template:
      src: templates/user.html.j2
      dest: "/var/www/html/dev1/{{user.name}}.html"
 
 # Create symbolic link
  - name: symbolique link creation
    file: 
      src: /home/osboxes/web_dev1 
      path: /var/www/html/{{user.name}}
      state: link
      force: true
  
 # http API request:
  - name:  http API requests
    uri:
      url: "{{endpoint}}"
      method: GET
    register: content
    
  - debug: var=content.url

...
