---
- name: TP eEXO 4
  hosts: slave1
  become: yes
  
  tasks:

  - name: Copy file scrip in slave1
    copy:
      src: files/system.sh
      dest: "system.sh"
      mode: '500'

  - name: "executing script"
    shell: ./system.sh 
    ignore_errors: yes
    register: output


  - name: show the value of output
    debug: var=output.stdout

# autre façon:
#     - name: Run a script
# ansible.builtin.script:
# path: /files
# cmd: ./system.sh
# register: system_out
...